<?php

// public/index.php

// Define the root directory for easier path management
define('ROOT_PATH', dirname(__DIR__));

// Autoload dependencies (will be generated by Composer)
if (file_exists(ROOT_PATH . '/vendor/autoload.php')) {
    require_once ROOT_PATH . '/vendor/autoload.php';
}

// Load configuration into the global scope so core functions can access it
global $config;
$config = require_once ROOT_PATH . '/config.php';

// Load and initialize the plugin system
require_once ROOT_PATH . '/src/plugins.php';
load_plugins($config);

// Load core functions
require_once ROOT_PATH . '/src/core.php';

// Basic routing
$page = $_GET['page'] ?? 'home';
$post_slug = $_GET['post'] ?? null;

// Route the request
if ($post_slug) {
    // Display a single post
    $post = get_post($config, $post_slug);
    if ($post) {
        render($config, 'post', ['post' => $post]);
    } else {
        // Simple 404 handling
        http_response_code(404);
        render($config, '404', []);
    }
} else {
    // Display the home page (list of all posts)
    $posts = get_all_posts($config);
    render($config, 'home', ['posts' => $posts]);
}
