<?php

// public/index.php

// Define the root directory for easier path management
define('ROOT_PATH', dirname(__DIR__));

// Autoload dependencies (will be generated by Composer)
if (file_exists(ROOT_PATH . '/vendor/autoload.php')) {
    require_once ROOT_PATH . '/vendor/autoload.php';
}

// Load configuration into the global scope so core functions can access it
global $config;
$config = require_once ROOT_PATH . '/config.php';

// Load and initialize the plugin system
require_once ROOT_PATH . '/src/plugins.php';
load_plugins($config);

// Load core functions
require_once ROOT_PATH . '/src/core.php';

// Load widget functions
require_once ROOT_PATH . '/src/widgets.php';

// Start session and load auth functions to check for admin login status on public site
if (file_exists(ROOT_PATH . '/admin/auth.php')) {
    require_once ROOT_PATH . '/admin/auth.php';
}

// Basic routing
$post_slug = $_GET['post'] ?? null;
$page_num = isset($_GET['paged']) ? (int)$_GET['paged'] : 1;

// Route the request
if ($post_slug) {
    // Display a single post
    $post = get_post($config, $post_slug);
    if ($post) {
        render($config, 'post', ['post' => $post]);
    } else {
        // Simple 404 handling
        http_response_code(404);
        render($config, '404', []);
    }
} else {
    // Display the home page with pagination
    $all_posts = get_all_posts($config);

    // Get settings from config, with defaults
    $posts_per_page = $config['posts_per_page'] ?? 10;
    $pagination_style = $config['pagination_style'] ?? 'numbered';

    // Calculate total pages and current page
    $total_posts = count($all_posts);
    $total_pages = ceil($total_posts / $posts_per_page);
    $current_page = max(1, min($page_num, $total_pages));

    // Get the subset of posts for the current page
    $offset = ($current_page - 1) * $posts_per_page;
    $paginated_posts = array_slice($all_posts, $offset, $posts_per_page);

    // Prepare pagination data for the theme
    $pagination_data = [
        'total_pages'  => $total_pages,
        'current_page' => $current_page,
        'style'        => $pagination_style,
    ];

    render($config, 'home', [
        'posts'      => $paginated_posts,
        'pagination' => $pagination_data,
    ]);
}